apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sso
spec:
  hosts:
  - sso
  http:
  - route:
    - destination:
        host: sso
        subset: v1
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sso
spec:
  host: sso
  subsets:
  - name: v1
    labels:
      version: v1
---